### ISSUE TITLE
Compatibility with Umbraco 8.11.1

### ISSUE THREAD

**Issue by akeilox** [vendrhub/vendr-checkout#13]
I am trying to give Vendr a spin so I installed the latest 8.11.1 version (tried both on IIS express and full IIS);
Install Vendr 1.5 goes fine, i can see the section under Settings.

However when I try installing Checkout package it doesnt seem to create any nodes, I cant seem to create any nodes from the root either.
Is this a SQLCE issue? I did standard install on both IIS.

Similarly when I search for Vendr Contrib Payment Providers
front-end shows"Package already installed" and error pops up indicating validation fails as exception.
It was my understanding if this was installed Paypal/Stripe will be shown under Settings-> Vendr but they are not there.

Would appreciate if you can shed some light.
cheers

**Comment by mattbrailsford** [comment]
Hi Akeilox,

Neither of these packages will create nodes automatically. Vendr Checkout requires you to use the dashboard installed in the settings section to install the relevant content. This is because Vendr support multiple stores so you are required to select the actual store you wish to install the package under before anything is created.

With payment providers, again, you still need to create the "Payment Methods" in your stores settings, installing the payment provider packages just makes those payment providers as selectable options.

Matt
