### ISSUE TITLE
Multilanguage support (in the checkout flow)

### ISSUE THREAD

**Issue by JasonElkin** [vendrhub/vendr-checkout#22]
Currently the views are hardcoded in English.

It would be better if they could be translated, or customised, without modifying the views directly.

@mattbrailsford I need to implement this for a project and can to contribute the changes back if you're happy with the approach.

Was thinking of just using the Dictionary with namespace-like keys e.g. "VendrCheckout.Confirmation.EmailSent" and using `string.Format()` compatible strings where necessary. e.g. "A confirmation email has been sent to {0}"

**Comment by JasonElkin** [comment]
@mattbrailsford I need to implement this for a project and can to contribute the changes back if you're happy with the approach.

Was thinking of just using the Dictionary with namespace-like keys e.g. "VendrCheckout.Confirmation.EmailSent" and using `string.Format()` compatible strings where necessary. e.g. "A confirmation email has been sent to {0}"

**Comment by mattbrailsford** [comment]
@JasonElkin absolutely! And yup, I agree, dictionary items would be the way to go 👍

**Comment by mattbrailsford** [comment]
Just worth noting, I've restructured this repository recently as I've reworked the package for use in Vendr v2 so you may need a clean fork if you created one previously. Also, you'll need to make sure to target the right version. If you are using Vendr v1x then you'll need to target `v1/dev` otherwise on Vendr v2 target `v2/dev`

**Comment by mattbrailsford** [comment]
Closing this issue as all latest views now use the dictionary for their values
